# Generated by Django 2.1 on 2019-11-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=models.FileField(blank=True, null=True, upload_to='articlePic/', verbose_name='文章插图'),
        ),
    ]
