# Generated by Django 2.1 on 2019-09-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecolumn',
            name='classify',
            field=models.IntegerField(default=1, verbose_name='栏目分类'),
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='column',
            field=models.CharField(max_length=100, verbose_name='栏目名称'),
        ),
    ]
