# Generated by Django 2.1 on 2019-04-16 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=100, verbose_name='标题')),
                ('brief_content', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('click', models.IntegerField(default=0, verbose_name='浏览量')),
                ('dianzan', models.IntegerField(default=0, verbose_name='点赞数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to=settings.AUTH_USER_MODEL)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to='itadmin.ArticleColumn')),
            ],
        ),
    ]
