# Generated by Django 2.1 on 2019-11-02 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0002_auto_20191031_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=models.ImageField(upload_to='img/', verbose_name='文章插图'),
        ),
    ]
