# Generated by Django 2.1 on 2019-11-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0003_auto_20191102_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=models.ImageField(upload_to='article_img/', verbose_name='文章插图'),
        ),
    ]
