# Generated by Django 2.1 on 2019-04-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0003_auto_20190416_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brief_content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
    ]
