# Generated by Django 2.1 on 2019-04-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0004_auto_20190416_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brief_content',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
    ]
