# Generated by Django 2.1 on 2019-11-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0004_auto_20191102_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=models.CharField(max_length=100, verbose_name='文章插图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
