# Generated by Django 2.1 on 2019-04-17 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itadmin', '0005_auto_20190416_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dianzan',
        ),
        migrations.AddField(
            model_name='article',
            name='user_dianzan',
            field=models.ManyToManyField(blank=True, related_name='article_dianzan', to=settings.AUTH_USER_MODEL, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='created_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='articlecolumn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
