# Generated by Django 2.1 on 2019-11-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0005_auto_20191102_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=models.ImageField(upload_to='articlePic/', verbose_name='文章插图'),
        ),
    ]
