# Generated by Django 2.1 on 2019-04-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0006_auto_20190417_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_dianzan',
            new_name='dianzan',
        ),
    ]
