# Generated by Django 2.1 on 2019-11-05 05:19

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0006_auto_20191102_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_pic',
            field=models.FileField(blank=True, null=True, upload_to='articlePic/', verbose_name='文章插图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
