# Generated by Django 2.1 on 2019-04-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0010_articletag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='article_tag', to='itadmin.ArticleTag', verbose_name='标签'),
        ),
    ]
