# Generated by Django 2.1 on 2019-04-19 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itadmin', '0011_article_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletag',
            old_name='author',
            new_name='user',
        ),
    ]
