# Generated by Django 2.1 on 2019-10-27 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(auto_now=True, verbose_name='最后一次登录时间')),
                ('last_login_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='最后一次登录ip')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('photo_url', models.ImageField(blank=True, null=True, upload_to='static/images/user/%Y_%m_%d', verbose_name='头像路径')),
                ('about', models.TextField(blank=True, default='记录自己生活点滴、互联网技术的原创', null=True, verbose_name='关于我')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
    ]
