# Generated by Django 2.1 on 2019-11-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprint',
            name='photo_size',
            field=models.IntegerField(default=1, verbose_name='照片尺寸'),
        ),
        migrations.AlterField(
            model_name='photoprint',
            name='print_number',
            field=models.IntegerField(default=1, verbose_name='打印份数'),
        ),
    ]
