# Generated by Django 2.1 on 2019-11-02 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprint', '0002_auto_20191102_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprint',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='订单创建时间'),
        ),
        migrations.AlterField(
            model_name='fileprint',
            name='file_url',
            field=models.ImageField(blank=True, null=True, upload_to='filePrint/%Y_%m_%d/', verbose_name='存储路径'),
        ),
        migrations.AlterField(
            model_name='photoprint',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='订单创建时间'),
        ),
        migrations.AlterField(
            model_name='photoprint',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='photoPrint/%Y_%m_%d/', verbose_name='存储路径'),
        ),
    ]
