# Generated by Django 2.1 on 2019-11-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprint', '0003_auto_20191102_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileprint',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='fileprint',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='photoprint',
            name='photo_name',
        ),
        migrations.RemoveField(
            model_name='photoprint',
            name='photo_type',
        ),
        migrations.AlterField(
            model_name='fileprint',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间'),
        ),
        migrations.AlterField(
            model_name='photoprint',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间'),
        ),
    ]
