# Generated by Django 2.1 on 2019-11-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprint', '0004_auto_20191102_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprint',
            name='price',
            field=models.CharField(max_length=100, verbose_name='总价格'),
        ),
        migrations.AlterField(
            model_name='photoprint',
            name='price',
            field=models.CharField(max_length=100, verbose_name='总价格'),
        ),
    ]
