# Generated by Django 2.1 on 2019-11-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprint', '0005_auto_20191102_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprint',
            name='page_count',
            field=models.IntegerField(default=0, verbose_name='总页数'),
        ),
        migrations.AlterField(
            model_name='fileprint',
            name='print_number',
            field=models.IntegerField(default=1, verbose_name='打印份数'),
        ),
    ]
