# Generated by Django 2.1 on 2019-11-02 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprint', '0006_auto_20191103_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprint',
            name='page_count',
            field=models.IntegerField(default=1, verbose_name='总页数'),
        ),
    ]
