# Generated by Django 2.1 on 2019-11-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprint', '0008_auto_20191103_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprint',
            name='color',
            field=models.IntegerField(default=1, verbose_name='打印彩色黑白'),
        ),
        migrations.AlterField(
            model_name='fileprint',
            name='sided',
            field=models.IntegerField(default=1, verbose_name='打印单双面'),
        ),
    ]
