# Generated by Django 2.1 on 2019-11-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oprint', '0010_auto_20191105_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileprint',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='filePrint/%Y_%m_%d/', verbose_name='存储路径'),
        ),
        migrations.AlterField(
            model_name='photoprint',
            name='photo_url',
            field=models.FileField(blank=True, null=True, upload_to='photoPrint/%Y_%m_%d/', verbose_name='存储路径'),
        ),
    ]
